---
services:
  dd-agent:
    image: gcr.io/datadoghq/agent:latest
    container_name: dd-agent
    environment:
      - DD_SITE=datadoghq.com
      - DD_API_KEY=""
      - DD_PROCESS_CONFIG_PROCESS_COLLECTION_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_SYSTEM_PROBE_SERVICE_MONITORING_ENABLED=true
    ports:
      - 8126:8126/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /sys/kernel/debug:/sys/kernel/debug
      - /lib/modules:/lib/modules
      - /usr/src:/usr/src
      - /var/tmp/datadog-agent/system-probe/build:/var/tmp/datadog-agent/system-probe/build
      - /var/tmp/datadog-agent/system-probe/kernel-headers:/var/tmp/datadog-agent/system-probe/kernel-headers
      - /etc/apt:/host/etc/apt
      - /etc/yum.repos.d:/host/etc/yum.repos.d
      - /etc/zypp:/host/etc/zypp
      - /etc/pki:/host/etc/pki
      - /etc/yum/vars:/host/etc/yum/vars
      - /etc/dnf/vars:/host/etc/dnf/vars
      - /etc/rhsm:/host/etc/rhsm
    cap_add:
      - SYS_ADMIN
      - SYS_RESOURCE
      - SYS_PTRACE
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
      - IPC_LOCK
      - CHOWN
    security_opt:
      - apparmor:unconfined
    labels:
      com.datadoghq.ad.logs: '[{"source": "datadog-agent", "service": "agent"}]'
    restart: always
