version: '3'
services:
    kerberos:
        image: kerberos/kerberos:latest
        restart: always
        container_name: kerberos-agent1
        privileged: true
        network_mode: "bridge"
        ports:
            - 8780:80
            - 8889:8889
        volumes:
            - ./agent1/config:/etc/opt/kerberosio/config:rw
            - /w/Security/kerberos/agent1:/etc/opt/kerberosio/capture:rw
            - ./agent1/logs:/etc/opt/kerberosio/logs:rw
            - ./agent1/webconfig:/var/www/web/config:rw
    kerberos-agent2:
        image: kerberos/kerberos:latest
        restart: always
        container_name: kerberos-agent2
        privileged: true
        network_mode: "bridge"
        ports:
            - 8782:80
            - 8879:8889
        volumes:
            - ./agent2/config:/etc/opt/kerberosio/config:rw
            - /w/Security/kerberos/agent2:/etc/opt/kerberosio/capture:rw
            - ./agent2/logs:/etc/opt/kerberosio/logs:rw
            - ./agent2/webconfig:/var/www/web/config:rw