services:
    kavita:
        image: jvmilazz0/kavita:latest    # Using the stable branch from the official dockerhub repo.
        container_name: kavita
        volumes:
            - /d/TheVault/Gotham-Library/Manga:/manga
            - /d/TheVault/Gotham-Library/Comics:/comics
            - /d/TheVault/Gotham-Library/Novels:/books
            - /d/TheVault/Gotham-Library/Self-improvement:/Self-improvement
            - /d/TheVault/Gotham-Library/Tech:/Tech
            - /d/TheVault/Gotham-Library/Cook-books:/Cook-books
            - /d/TheVault/Gotham-Library/Magazines:/Magazines
            - ./config:/kavita/config     # /kavita/config must not be changed
        environment:
            - TZ=America/New_York
            - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true
        ports:
            - "5090:5000"
        restart: unless-stopped
        networks:
          - robo54

networks:
  robo54:
    external: true