---
services:
  mealie:
    #image: ghcr.io/mealie-recipes/mealie:v1.3.2
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    ports:
        - "9925:9000"
    deploy:
      resources:
        limits:
          memory: 1500M
    volumes:
      - ./mealie-data:/app/data/
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=true
      - TZ=America/New_York
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=""
    restart: unless-stopped
    networks:
      - robo54

networks:
  robo54:
    external: true