services:
  multi-scrobbler:
    image: foxxmd/multi-scrobbler
    container_name: multi-scrobbler
    environment:
      - TZ=America/New_york** # Specify timezone from TZ Database name found here https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - SPOTIFY_CLIENT_ID=""
      - SPOTIFY_CLIENT_SECRET=""
      - SPOTIFY_REDIRECT_URI=http://192.168.1.160:9078/callback ## Need to be whitelisted in Spotify dashboard and is used for creating the connection first time
      - MALOJA_URL=http://192.168.1.160:42010
      - MALOJA_API_KEY=""
      - PLEX_URL=http://192.168.1.160:32400
      - PLEX_TOKEN=""
      - PLEX_USERS_ALLOW=""
      - PLEX_LIBRARIES_BLOCK= "Audio Books"
      #- PUID=1000 # required if running docker on linux host, see main README Docker setup instructions
      #- PGID=1000 # required if running docker on linux host, see main README Docker setup instructions

      # set if using a source/client with redirect URI that you have not explicitly set and MS is NOT running on the same machine that you will view the dashboard from
      # EX: You will view MS dashboard at 'http://192.168.0.101:9078' -> set BASE_URL=http://192.168.0.101:9078
      #- BASE_URL=http://MyHostIP:9078
    volumes:
      - "./config:/config"
    #networks:
    #  - (optional to add container to the same bridge network that maloja is inside to be able to use docker internal networking & dns to resolve and connect to maloja URL via http://maloja:port)
    ports:
      - 9078:9078 # first port is the HOST port multi-scrobbler will serve UI and API on
    restart: unless-stopped