---
services:
  slskd:
    image: slskd/slskd
    container_name: slskd
    ports:
      - "5030:5030"
      - "5031:5031"
      - "5032:50300"
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
    volumes:
      - ./data:/app
      - /d/Downloads/automation/slskd:/Downloads
      - /d/Downloads/automation/music/incomplete:/Downloads/incomplete
    restart: unless-stopped