services:
  trilium:
    image: triliumnext/notes:latest
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    ports:
      - "3080:8080"
    volumes:
      - ./trillium:/home/node/trilium-data