services:
  db:
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=""
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=""
      - MYSQL_PASSWORD=""
    expose:
      - 3306
      - 33060
    networks:
      - robo54  # Attach db to robo54 network

  wordpress:
    image: wordpress:latest
    ports:
      - 6080:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=""
      - WORDPRESS_DB_PASSWORD=""
      - WORDPRESS_DB_NAME=""
    networks:
      - robo54  # Attach wordpress to robo54 network

networks:
  robo54:
    external: true
